spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: lb://CUSTOMERS-SERVICE
            predicates:
              - Path= /api/customers/**
          - id: r2
            uri: lb://INVENTORY-SERVICA
            predicates:
              - Path= /api/products/**

